<?php

/*
English names:

return [
    "Abobada",
    "Abrantes",
    "Acores",
    "Aguada de Cima",
    "Agualva",
    "Agucadoura",
    "Aguiar da Beira Municipality",
    "Alandroal",
    "Albergaria-a-Velha",
    "Albufeira",
    "Alcabideche",
    "Alcacer do Sal",
    "Alcains",
    "Alcanede",
    "Alcanena",
    "Alcobaca",
    "Alcochete",
    "Alcoentre",
    "Aldeia de Paio Pires",
    "Aldeia do Meio",
    "Aldeia dos Fernandes",
    "Alenquer",
    "Alfarelos",
    "Alfena",
    "Alfornelos",
    "Alfragide",
    "Alges",
    "Algoz",
    "Algueirao",
    "Alhandra",
    "Alhos Vedros",
    "Aljezur",
    "Aljustrel",
    "Almada",
    "Almancil",
    "Almargem",
    "Almeirim",
    "Almodovar",
    "Alpiarca",
    "Alportel",
    "Alqueidao da Serra",
    "Alter do Chao",
    "Altura",
    "Alvaiazere",
    "Alvarinhos",
    "Alvelos",
    "Alverca",
    "Amadora",
    "Amarante",
    "Amares",
    "Amiaes de Cima",
    "Amor",
    "Amora",
    "Amoreira",
    "Amorim",
    "Anadia",
    "Anta",
    "Apulia",
    "Arazede",
    "Arco da Calheta",
    "Arcos de Valdevez",
    "Arcozelo",
    "Arganil",
    "Argoncilhe",
    "Armacao de Pera",
    "Arouca",
    "Arraiolos",
    "Arrifana",
    "Arronches",
    "Arruda dos Vinhos",
    "Arvore",
    "Assumar",
    "Atalaia",
    "Atouguia da Baleia",
    "Avanca",
    "Aveiras de Cima",
    "Aveiro",
    "Avelar",
    "Avidos",
    "Avintes",
    "Azoia",
    "Azueira",
    "Azurem",
    "Baguim",
    "Baguim do Monte",
    "Baleia",
    "Baltar",
    "Barcarena",
    "Barcelos",
    "Barreiro",
    "Barrosas",
    "Basto",
    "Batalha",
    "Beira",
    "Beja",
    "Belas",
    "Belmonte",
    "Bemfica",
    "Benafim",
    "Benavente",
    "Benedita",
    "Bicesse",
    "Bico",
    "Boavista",
    "Bobadela",
    "Boliqueime",
    "Bombarral",
    "Borba",
    "Boticas",
    "Bouca",
    "Braga",
    "Braganca",
    "Brito",
    "Bucelas",
    "Buraca",
    "Cabanelas",
    "Cabeceiras de Basto",
    "Cabeco de Vide",
    "Cabecudos",
    "Cabrela",
    "Cacela",
    "Cacem",
    "Cacilhas",
    "Cadaval",
    "Caldas",
    "Caldas da Rainha",
    "Caldas das Taipas",
    "Caldas de Sao Jorge",
    "Caldas de Vizela",
    "Calvao",
    "Calvaria de Cima",
    "Camarate",
    "Caminha",
    "Campanario",
    "Campia",
    "Campinho",
    "Campo",
    "Campo Maior",
    "Canecas",
    "Canedo",
    "Canelas",
    "Canhas",
    "Canical",
    "Canico",
    "Canidelo",
    "Cano",
    "Cantanhede",
    "Caparica",
    "Caramulo",
    "Carapinheira",
    "Carcavelos",
    "Carnaxide",
    "Carrazedo",
    "Carregado",
    "Carrico",
    "Cartaxo",
    "Carvalhal",
    "Carvalho",
    "Carvalhosa",
    "Carvoeiro",
    "Casal",
    "Casal da Areia",
    "Cascais",
    "Castanheira do Ribatejo",
    "Castelejo",
    "Castelo",
    "Castelo Branco",
    "Castelo de Paiva",
    "Castro Daire",
    "Castro Marim",
    "Castro Verde Municipality",
    "Catraia de Sao Paio",
    "Cavaleiros",
    "Cavaloes",
    "Caxias",
    "Ceira",
    "Celorico de Basto",
    "Cercal",
    "Cernache",
    "Cesar",
    "Chao de Couce",
    "Charneca",
    "Chaves",
    "Cidade",
    "Cinfaes",
    "Coimbra",
    "Colares",
    "Colmeias",
    "Condeixa-a-Nova",
    "Constance",
    "Constancia",
    "Corroios",
    "Cortegaca",
    "Costa de Caparica",
    "Costa de Lavos",
    "Covilha",
    "Creixomil",
    "Cruz Quebrada",
    "Cuba",
    "Cucujaes",
    "Dalvares",
    "Damaia",
    "Darque",
    "Dois Portos",
    "Dona Maria",
    "Dossaos",
    "Eixo",
    "Elvas",
    "Encarnacao",
    "Entroncamento",
    "Ericeira",
    "Ermidas",
    "Escapaes",
    "Escoural",
    "Esmoriz",
    "Espinho",
    "Esposende",
    "Estarreja",
    "Estoi",
    "Estombar",
    "Estoril",
    "Estremoz",
    "Evora",
    "Fafe",
    "Famoes",
    "Fanzeres",
    "Fao",
    "Faro",
    "Feira",
    "Felgueiras",
    "Ferradosa",
    "Ferreira",
    "Ferreira do Alentejo",
    "Ferrel",
    "Ferro",
    "Fiaes",
    "Figueira da Foz Municipality",
    "Figueira de Lorvao",
    "Figueiro dos Vinhos",
    "Fogueteiro",
    "Folgados",
    "Forte",
    "Foz do Sousa",
    "Fradelos",
    "Freamunde",
    "Frielas",
    "Funchal",
    "Fundao",
    "Gafanha da Nazare",
    "Galiza",
    "Gandara dos Olivais",
    "Gandra",
    "Garruchas",
    "Gemunde",
    "Godim",
    "Golega",
    "Gondomar",
    "Gouveia",
    "Graca",
    "Gradil",
    "Grandola",
    "Granja",
    "Granja do Ulmeiro",
    "Grijo",
    "Guarda",
    "Guardizela",
    "Guia",
    "Guimaraes",
    "Gulpilhares",
    "Igreja Nova",
    "Ilhavo",
    "Infesta",
    "Joane",
    "Jovim",
    "Juncal",
    "Lagarinhos",
    "Lago",
    "Lagoa",
    "Lagoas",
    "Lagos",
    "Lajes",
    "Lamego",
    "Landim",
    "Lavos",
    "Lavra",
    "Lavradio",
    "Leca da Palmeira",
    "Leca do Bailio",
    "Leiria",
    "Linda a Velha",
    "Linhaceira",
    "Linho",
    "Lisbon",
    "Lordelo",
    "Loule",
    "Lourel de Baixo",
    "Loures",
    "Lourical",
    "Lourosa",
    "Lousa",
    "Lousada",
    "Lousado",
    "Macas de Caminho",
    "Maceda",
    "Macedo de Cavaleiros",
    "Maceira",
    "Machico",
    "Macieira da Lixa",
    "Madeira",
    "Mafra",
    "Maia",
    "Malveira",
    "Malveira da Serra",
    "Mamouros",
    "Mangualde",
    "Manique de Baixo",
    "Manique do Intendente",
    "Marco",
    "Marco de Canaveses",
    "Margaride",
    "Marinha",
    "Marinha Grande",
    "Marinhais",
    "Marteleira",
    "Martinganca",
    "Massama",
    "Massarelos",
    "Matosinhos Municipality",
    "Mealhada",
    "Mem Martins",
    "Mesao Frio",
    "Mexilhoeira Grande",
    "Milharado",
    "Milhazes",
    "Minde",
    "Mira",
    "Miranda do Corvo",
    "Miranda do Douro",
    "Mirandela",
    "Mocarria",
    "Modivas",
    "Moita",
    "Moncao",
    "Monchique",
    "Monforte",
    "Monsanto",
    "Monsaraz",
    "Montalvo",
    "Monte Estoril",
    "Montelavar",
    "Montemor-o-Novo",
    "Montemor-o-Velho",
    "Montes",
    "Montijo",
    "Moreira de Conegos",
    "Mortagua",
    "Moscavide",
    "Moura",
    "Moure",
    "Mourisca do Vouga",
    "Mozelos",
    "Muro",
    "Murtede",
    "Murteira",
    "Nadadouro",
    "Negrelos",
    "Neiva",
    "Nelas",
    "Nespereira",
    "Nine",
    "Nisa",
    "Nogueira",
    "Nogueira da Regedoura",
    "Nogueira do Cravo",
    "Obidos",
    "Odemira",
    "Odivelas",
    "Oeiras",
    "Oia",
    "Olhao",
    "Olhos de Agua",
    "Olivais",
    "Olival",
    "Oliveira",
    "Oliveira do Bairro",
    "Oliveira do Douro",
    "Oliveira do Hospital",
    "Ortiga",
    "Ota",
    "Ourem",
    "Ourique",
    "Outeiro",
    "Ovar",
    "Paco de Arcos",
    "Paderne",
    "Palhaca",
    "Palhais",
    "Palmeira",
    "Palmela",
    "Parada de Gonta",
    "Parada do Bispo",
    "Paraiso",
    "Parchal",
    "Pardilho",
    "Parede",
    "Paredes",
    "Paredes da Beira",
    "Paredes de Coura",
    "Pataias",
    "Paul",
    "Pechao",
    "Pedreiras",
    "Pedroso",
    "Pedroucos",
    "Pegoes Velhos",
    "Penacova",
    "Penafiel",
    "Penedono",
    "Penela",
    "Penha Garcia",
    "Peniche",
    "Penteado",
    "Pereira",
    "Pero Pinheiro",
    "Pevidem",
    "Piedade",
    "Pinhal",
    "Pinhal Novo",
    "Pinheiro",
    "Pinheiro da Bemposta",
    "Pinheiro de Azere",
    "Poceirao",
    "Poco Barreto",
    "Poiares",
    "Polima",
    "Pombal",
    "Ponta",
    "Ponta Delgada",
    "Ponta do Sol",
    "Ponte",
    "Ponte da Barca",
    "Ponte de Lima",
    "Ponte de Sor",
    "Ponte de Vagos",
    "Pontevel",
    "Pontinha",
    "Portalegre",
    "Portel",
    "Portela",
    "Portimao",
    "Porto",
    "Porto Alto",
    "Porto da Cruz",
    "Porto de Mos",
    "Porto Moniz",
    "Porto Salvo",
    "Povoa",
    "Povoa da Galega",
    "Povoa de Lanhoso",
    "Povoa de Santa Iria",
    "Povoa de Santo Adriao",
    "Povoa do Forno",
    "Prado",
    "Pragal",
    "Praia da Vitoria",
    "Praia de Mira",
    "Praia do Almoxarife",
    "Praia do Carvoeiro",
    "Praia do Ribatejo",
    "Prazins",
    "Prime",
    "Proenca-a-Nova",
    "Quarteira",
    "Quejas",
    "Queluz",
    "Queluz de Baixo",
    "Quinchaes",
    "Quinta",
    "Quinta do Anjo",
    "Ramada",
    "Ramo",
    "Rana",
    "Real",
    "Rebordosa",
    "Recarei",
    "Redondo",
    "Regueira de Pontes",
    "Reguengo Grande",
    "Reguengos de Monsaraz",
    "Riachos",
    "Riba de Ave",
    "Ribeira Brava",
    "Ribeira Grande",
    "Ribeirao",
    "Rinchoa",
    "Rio de Moinhos",
    "Rio de Mouro",
    "Rio Maior",
    "Rio Tinto",
    "Romariz",
    "Ronfe",
    "Roque",
    "Roriz",
    "Runa",
    "Sabugal",
    "Sacavem",
    "Salreu",
    "Salto",
    "Salvaterra de Magos",
    "Samil",
    "Samora Correia",
    "Samouco",
    "Sandim",
    "Sanfins do Douro",
    "Sangalhos",
    "Sanguedo",
    "Santa Barbara de Nexe",
    "Santa Catarina",
    "Santa Catarina da Serra",
    "Santa Clara-a-Velha",
    "Santa Comba Dao",
    "Santa Cruz",
    "Santa Iria da Azoia",
    "Santa Marta",
    "Santa Marta de Penaguiao",
    "Santana",
    "Santiago",
    "Santiago da Guarda",
    "Santiago de Riba-Ul",
    "Santiago do Cacem",
    "Santo Andre",
    "Santo Antao do Tojal",
    "Santo Antonio",
    "Santo Antonio da Charneca",
    "Santo Tirso",
    "Sao Bras",
    "Sao Bras de Alportel",
    "Sao Domingos de Rana",
    "Sao Felix da Marinha",
    "Sao Francisco",
    "Sao Joao",
    "Sao Joao da Madeira",
    "Sao Joao da Talha",
    "Sao Joao das Lampas",
    "Sao Joao de Ver",
    "Sao Joao do Campo",
    "Sao Joao dos Montes",
    "Sao Juliao do Tojal",
    "Sao Mamede de Infesta",
    "Sao Marcos",
    "Sao Pedro da Cadeira",
    "Sao Pedro do Estoril",
    "Sao Romao do Coronado",
    "Sao Roque",
    "Sao Vicente da Beira",
    "Sao Vicente de Lafoes",
    "Sardoal",
    "Sarilhos Grandes",
    "Satao",
    "Seia",
    "Seixal",
    "Sendim",
    "Senhora da Hora",
    "Seroa",
    "Serpa",
    "Serpins",
    "Serta",
    "Sesimbra",
    "Sete Rios",
    "Sever do Vouga",
    "Silva",
    "Silvares",
    "Silveira",
    "Silves",
    "Sines Municipality",
    "Sintra",
    "Soalheira",
    "Sobrado",
    "Sobrado de Paiva",
    "Sobral de Monte Agraco",
    "Sobralinho",
    "Sobreda",
    "Sobreiro",
    "Sobrosa",
    "Soito",
    "Soure Municipality",
    "Souto da Carpalhosa",
    "Souzel",
    "Sul",
    "Tabuaco",
    "Talaide",
    "Tamel",
    "Tarouca",
    "Taveiro",
    "Tavira Municipality",
    "Teixoso",
    "Telhado",
    "Tercena",
    "Terena",
    "Tires",
    "Tocha",
    "Tomar",
    "Tondela",
    "Torre da Marinha",
    "Torre de Moncorvo",
    "Torres Novas",
    "Torres Vedras",
    "Touguinha",
    "Tourais",
    "Trafaria",
    "Trancoso",
    "Trancoso de Baixo",
    "Travanca",
    "Treixedo",
    "Trofa",
    "Tunes",
    "Turcifal",
    "Vagos",
    "Valado de Frades",
    "Valbom",
    "Vale",
    "Vale da Pinta",
    "Vale de Acor",
    "Vale de Cambra",
    "Valega",
    "Valenca",
    "Valongo",
    "Valverde",
    "Varzea do Douro",
    "Venda do Pinheiro",
    "Vendas Novas",
    "Vermelha",
    "Vermoil",
    "Vialonga",
    "Viana do Alentejo",
    "Viana do Castelo",
    "Vidago",
    "Vidigueira",
    "Vieira de Leiria",
    "Vieira do Minho",
    "Vila Alva",
    "Vila Boa de Quires",
    "Vila Cha",
    "Vila Cha de Ourique",
    "Vila de Porto Santo",
    "Vila do Bispo",
    "Vila do Conde",
    "Vila Franca de Xira",
    "Vila Franca do Rosario",
    "Vila Nogueira de Azeitao",
    "Vila Nova",
    "Vila Nova da Barquinha",
    "Vila Nova de Cerveira",
    "Vila Nova de Famalicao",
    "Vila Nova de Gaia",
    "Vila Nova de Paiva",
    "Vila Praia de Ancora",
    "Vila Real",
    "Vila Verde",
    "Vilar de Perdizes",
    "Vilar do Paraiso",
    "Vilar do Pinheiro",
    "Vilar Formoso",
    "Vilarinho das Paranheiras",
    "Vilarinho de Arcos",
    "Vilarinho do Bairro",
    "Vilela",
    "Vimieiro",
    "Vinhais",
    "Viseu",
    "Vizela",
    "Zambujal",
    "Zibreira",
    "Águeda",
    "Aradas",
    "Arcos",
    "Beduido",
    "Branca",
    "Cortegaça",
    "Cucujães",
    "Esgueira",
    "Espargo",
    "Fiães",
    "Gafanha da Encarnação",
    "Gafanha da Nazaré",
    "Ílhavo",
    "Lamas",
    "Lobão",
    "Luso",
    "Macieira de Cambra",
    "Milheirós de Poiares",
    "Mosteirô",
    "Murtosa",
    "Oiã",
    "Oliveira de Azemeis",
    "Oliveira de Azeméis",
    "Oliveirinha",
    "Paços de Brandão",
    "Pampilhosa do Botão",
    "Pardilhó",
    "Rio Meão",
    "Sanfins",
    "Santa Maria da Feira",
    "São João",
    "São João da Madeira",
    "São João de Ver",
    "São Roque",
    "Silvalde",
    "Souto",
    "Válega",
    "Vila Chã",
    "Água de Pau",
    "Angra do Heroísmo",
    "Angústias",
    "Arrifes",
    "Biscoitos",
    "Cabouco",
    "Cais do Pico",
    "Calheta",
    "Calheta de São Jorge",
    "Corvo",
    "Fajã de Baixo",
    "Fenais da Ajuda",
    "Fenais da Luz",
    "Feteira",
    "Fonte Bastardo",
    "Furnas",
    "Horta",
    "Lajes das Flores",
    "Lajes do Pico",
    "Madalena",
    "Mosteiros",
    "Nordeste",
    "Ponta Garça",
    "Porto Judeu",
    "Porto Martins",
    "Povoação",
    "Praia da Vitória",
    "Rabo de Peixe",
    "Relva",
    "Ribeira Seca",
    "Ribeirinha",
    "Rosto de Cão",
    "Santa Bárbara",
    "Santa Cruz da Graciosa",
    "Santa Cruz das Flores",
    "São Bartolomeu",
    "São Mateus",
    "São Roque do Pico",
    "São Sebastião",
    "São Vicente",
    "Senhora do Rosário",
    "Velas",
    "Vila do Porto",
    "Vila Franca do Campo",
    "Aldeia Nova de São Bento",
    "Almodôvar",
    "Almograve",
    "Alvito",
    "Barrancos",
    "Beringel",
    "Boavista dos Pinheiros",
    "Cabeça Gorda",
    "Castro Verde",
    "Mértola",
    "Minas de São Domingos",
    "Neves",
    "Penedo Gordo",
    "Salvada",
    "São Luis",
    "São Teotónio",
    "Vila Nova de Milfontes",
    "Zambujeira do Mar",
    "Adaúfe",
    "Apúlia",
    "Apúlia e Fão",
    "Arões",
    "Aveleda",
    "Barqueiros",
    "Caldelas",
    "Calendário",
    "Candoso",
    "Chavão",
    "Cristelo",
    "Esporões",
    "Faria",
    "Ferreiros",
    "Frossos",
    "Galegos",
    "Gondizalves",
    "Gueral",
    "Guimarães",
    "Guisande",
    "Macieira de Rates",
    "Marinhas",
    "Mariz",
    "Merelim",
    "Negreiros",
    "Perelhal",
    "Póvoa de Lanhoso",
    "Refojos de Basto",
    "Rendufe",
    "Ribeirão",
    "Sande",
    "Selho",
    "Semelhe",
    "Serzedelo",
    "Serzedo",
    "Tebosa",
    "Terras de Bouro",
    "Urgeses",
    "Várzea",
    "Vila Cova",
    "Vila Frescainha",
    "Vila Nova de Famalicão",
    "Vila Seca",
    "Vilaça",
    "Vilar de Figos",
    "Alfândega da Fé",
    "Belver",
    "Bragança Municipality",
    "Carrazeda de Anciães",
    "Carrazeda de Ansiães",
    "Freixo de Espada à Cinta",
    "Mogadouro",
    "Vila Flor",
    "Vimioso",
    "Aldeia de Joanes",
    "Covilhã",
    "Fundão",
    "Idanha-A-Nova",
    "Oleiros",
    "Penamacor",
    "Proença-a-Nova",
    "Sertã",
    "Vila de Rei",
    "Vila Velha de Ródão",
    "Alhadas",
    "Ançã",
    "Assafarge",
    "Buarcos",
    "Figueira da Foz",
    "Góis",
    "Lorvão",
    "Lousã",
    "Oliveira do Mondego",
    "Pampilhosa da Serra",
    "Santa Clara",
    "Santo António dos Olivais",
    "São Pedro de Alva",
    "Soure",
    "Tábua",
    "Tavarede",
    "Vila Nova de Poiares",
    "Évora",
    "Mora",
    "Mourão",
    "Vila Viçosa",
    "Alcantarilha",
    "Alcoutim",
    "Alvor",
    "Armação de Pêra",
    "Bensafrim",
    "Cabanas de Tavira",
    "Conceição",
    "Estói",
    "Estômbar",
    "Ferragudo",
    "Ferreiras",
    "Fuzeta",
    "Laranjeiro",
    "Loulé",
    "Luz",
    "Manta Rota",
    "Marmelete",
    "Moncarapacho",
    "Monte Gordo",
    "Olhão",
    "Olhos de Água",
    "Pêra",
    "Porches",
    "Portimão",
    "Sagres",
    "Santa Bárbara de Nexe",
    "Santa Luzia",
    "São Bartolomeu de Messines",
    "São Brás de Alportel",
    "São Marcos da Serra",
    "Senhora da Luz",
    "Tavira",
    "Vila Nova De Cacela",
    "Vila Real de Santo António",
    "Vilamoura",
    "Abrigada",
    "Açores",
    "Adão",
    "Águas Belas",
    "Aguiar da Beira",
    "Ajuda",
    "Albardo",
    "Alcântara",
    "Aldeia da Ponte",
    "Aldeia da Ribeira",
    "Aldeia de Santo António",
    "Aldeia do Bispo",
    "Aldeia Galega da Merceana",
    "Aldeia Gavinha",
    "Aldeia Nova, Miranda do Douro",
    "Aldeia Velha",
    "Aldeia Viçosa",
    "Aldeias",
    "Alfaiates",
    "Algés",
    "Algodres",
    "Alguber",
    "Algueirão",
    "Algueirão–Mem Martins",
    "Almargem do Bispo",
    "Almeida",
    "Almendra",
    "Almofala",
    "Alto do Pina",
    "Alvalade",
    "Alvendre",
    "Alverca da Beira",
    "Alverca do Ribatejo",
    "Alvoco da Serra",
    "Ameixoeira",
    "Anjos",
    "Apelação",
    "Arranhó",
    "Arruda Dos Vinhos",
    "Aveiras de Baixo",
    "Avelãs da Ribeira",
    "Aveloso",
    "Azambuja",
    "Azambuja (town)",
    "Azenhas do Mar",
    "Azevo",
    "Baraçal",
    "Barreira",
    "Beato",
    "Bendada",
    "Benespera",
    "Benfica",
    "Bismula",
    "Bouça Cova",
    "Brandoa",
    "Cabanas de Torres",
    "Cabeça",
    "Cachoeiras",
    "Cadafais",
    "Cadafaz",
    "Calhandriz",
    "Campelos",
    "Campo Grande",
    "Campolide",
    "Caneças",
    "Carapito",
    "Cardosas",
    "Carmões",
    "Carnicães",
    "Carnide",
    "Carnota",
    "Carragozela",
    "Carrapichana",
    "Carvoeira",
    "Casal de Cambra",
    "Casal de Cinza",
    "Casal Vasco",
    "Casas do Soeiro",
    "Castanheira",
    "Casteição",
    "Casteleiro",
    "Castelo (Lisbon)",
    "Castelo Bom",
    "Castelo Melhor",
    "Castelo Rodrigo",
    "Cativelos",
    "Cavadoude",
    "Cedovim",
    "Celorico da Beira",
    "Cerdeira",
    "Cerejo",
    "Chãs",
    "Cheleiros",
    "Codesseiro",
    "Cogula",
    "Coração de Jesus",
    "Coriscada",
    "Cortiçada",
    "Cortiçô",
    "Cortiçô da Serra",
    "Coruche",
    "Corujeira",
    "Cótimos",
    "Cruz Quebrada - Dafundo",
    "Custoias",
    "Dornelas",
    "Eirado",
    "Encarnação",
    "Enxara do Bispo",
    "Ervas Tenras",
    "Ervedosa",
    "Escalhão",
    "Faia",
    "Falagueira",
    "Famalicão",
    "Famões",
    "Fanhões",
    "Fernão Joanes",
    "Figueira de Castelo Rodrigo",
    "Figueira do Guincho",
    "Figueiró da Granja",
    "Figueiró da Serra",
    "Figueiros",
    "Fóios",
    "Folgosinho",
    "Folhadosa",
    "Fontanelas",
    "Fonte Longa",
    "Forninhos",
    "Forno Telheiro",
    "Fornos de Algodres",
    "Forte da Casa",
    "Freches",
    "Freineda",
    "Freiria",
    "Freixeda do Torrão",
    "Freixedas",
    "Freixo",
    "Freixo de Numão",
    "Gagos",
    "Girabolhos",
    "Gonçalo",
    "Gonçalo Bocas",
    "Graça",
    "Gradiz",
    "Guilheiro",
    "Infias",
    "Jarmelo São Miguel",
    "Jarmelo São Pedro",
    "João Antão",
    "Junça",
    "Juncais",
    "Lajeosa",
    "Lajeosa do Mondego",
    "Lamegal",
    "Lameiras",
    "Lapa",
    "Lapa Dos Dinheiros",
    "Leomil",
    "Linda-a-Velha",
    "Linhares (Celorico da Beira)",
    "Longroiva",
    "Loriga",
    "Lourinhã",
    "Lumiar",
    "Maçainhas",
    "Maçal do Chão",
    "Maçussa",
    "Malcata",
    "Malhada Sorda",
    "Malpartida",
    "Mangualde da Serra",
    "Manigoto",
    "Manteigas",
    "Manteigas (São Pedro)",
    "Marialva",
    "Marmeleiro",
    "Mártires",
    "Marvila",
    "Massamá",
    "Mata de Lobos",
    "Matacães",
    "Matança",
    "Maxial",
    "Meca",
    "Mêda",
    "Meios",
    "Melo",
    "Mercês",
    "Mesquitela",
    "Mina",
    "Minhocal",
    "Mira-Sintra",
    "Miragaia",
    "Miuzela",
    "Mizarela",
    "Moimenta da Serra",
    "Moimentinha",
    "Moita dos Ferreiros",
    "Moledo",
    "Monte Abraão",
    "Monte Redondo",
    "Moreira de Rei",
    "Mós",
    "Murça",
    "Muxagata",
    "Nabais",
    "Nave",
    "Nave de Haver",
    "Nossa Senhora de Fátima",
    "Numão",
    "Odivelas Municipality",
    "Oeiras e São Julião da Barra",
    "Olhalvo",
    "Olival de Basto",
    "Olival do Basto",
    "Outeiro da Cabeça",
    "Outeiro de Gatos",
    "Paço de Arcos",
    "Paços da Serra",
    "Painho",
    "Pala",
    "Panoias de Cima",
    "Parada",
    "Paranhos",
    "Pega",
    "Pena",
    "Pena Lobo",
    "Pena Verde",
    "Penha de Águia",
    "Penha de França",
    "Pêra do Moço",
    "Peral",
    "Pereiro",
    "Pereiro de Palhacana",
    "Pêro Moniz",
    "Peva",
    "Pinhanços",
    "Pinhel",
    "Pínzio",
    "Poço do Canto",
    "Pomares",
    "Ponte do Rol",
    "Porto da Carne",
    "Pousada",
    "Pousafoles do Bispo",
    "Póvoa de Santa Iria",
    "Póvoa de Santo Adrião",
    "Póvoa do Concelho",
    "Prados",
    "Prazeres",
    "Prior Velho",
    "Prova",
    "Quadrazais",
    "Queijas",
    "Queiriz",
    "Quintã de Pêro Martins",
    "Quintas de São Bartolomeu",
    "Rabaçal",
    "Ramalhal",
    "Ramela",
    "Ranhados",
    "Rapa",
    "Rapoula do Côa",
    "Ratoeira",
    "Reboleira",
    "Reboleiro",
    "Rebolosa",
    "Reigada",
    "Rendo",
    "Ribafria",
    "Ribamar",
    "Ribamondego",
    "Ribeira Dos Carinhos",
    "Rio de Mel",
    "Rio Torto",
    "Rochoso",
    "Ruvina",
    "Sabugueiro",
    "Sacavém",
    "Sacramento",
    "Safurdão",
    "Salgueirais",
    "Sameice",
    "Sameiro",
    "Sandomil",
    "Santa Comba",
    "Santa Engrácia",
    "Santa Eufémia",
    "Santa Eulália",
    "Santa Iria da Azóia",
    "Santa Iria de Azoia",
    "Santa Isabel",
    "Santa Justa",
    "Santa Maria",
    "Santa Maria de Belém",
    "Santa Maria do Castelo e São Miguel",
    "Santa Maria dos Olivais",
    "Santa Maria e São Miguel",
    "Santa Marinha",
    "Santana da Azinha",
    "Santiago dos Velhos",
    "Santo Antão do Tojal",
    "Santo António dos Cavaleiros",
    "Santo Condestável",
    "Santo Estêvão",
    "Santo Estêvão das Galés",
    "Santo Isidoro",
    "Santo Quintino",
    "Santos-o-Velho",
    "São Bartolomeu dos Galegos",
    "São Brás",
    "São Cristóvão e São Lourenço",
    "São Domingos de Benfica",
    "São Domingos de Rana",
    "São Francisco Xavier",
    "São João da Talha",
    "São João das Lampas",
    "São João de Brito",
    "São João de Deus",
    "São João Dos Montes",
    "São Jorge de Arroios",
    "São José",
    "São Julião",
    "São Julião do Tojal",
    "São Mamede",
    "São Marcos",
    "São Martinho",
    "São Miguel",
    "São Miguel da Guarda",
    "São Miguel de Alcainça",
    "São Nicolau",
    "São Paio",
    "São Paulo",
    "São Pedro",
    "São Pedro da Cadeira",
    "São Pedro de Penaferrim",
    "São Pedro de Rio Seco",
    "São Romão",
    "São Sebastião da Pedreira",
    "São Vicente de Fora",
    "Sapataria",
    "Sazes da Beira",
    "Sé",
    "Sebadelhe",
    "Sebadelhe da Serra",
    "Seixas",
    "Seixo do Côa",
    "Sequeira",
    "Sequeiros",
    "Sintra (town)",
    "Sobral da Abelheira",
    "Sobral da Serra",
    "Sobral de Monte Agraço",
    "Sobral Pichorro",
    "Socorro",
    "Sortelha",
    "Souro Pires",
    "Souto de Aguiar da Beira",
    "Souto Maior",
    "Tamanhos",
    "Teixeira",
    "Terrenho",
    "Terrugem",
    "Torre do Terrenho",
    "Torres",
    "Torrozelo",
    "Touça",
    "Travancinha",
    "Triana",
    "Trinta",
    "Unhos",
    "Valdujo",
    "Vale da Mula",
    "Vale de Amoreira",
    "Vale de Azares",
    "Vale de Espinho",
    "Vale de Estrela",
    "Vale do Paraíso",
    "Vale do Seixo",
    "Vale Flor",
    "Valezim",
    "Valhelhas",
    "Várzea de Meruge",
    "Vascoveiro",
    "Vela",
    "Velosa",
    "Venda Nova",
    "Venteira",
    "Ventosa",
    "Vermiosa",
    "Vide",
    "Vide Entre Vinhas",
    "Videmonte",
    "Vila Boa",
    "Vila Boa do Mondego",
    "Vila Cortês da Serra",
    "Vila Cortês do Mondego",
    "Vila Cova à Coelheira",
    "Vila do Touro",
    "Vila Fernando",
    "Vila Franca da Serra",
    "Vila Franca das Naves",
    "Vila Franca do Deão",
    "Vila Franca do Rosário",
    "Vila Garcia",
    "Vila Nova da Rainha",
    "Vila Nova de Foz Côa",
    "Vila Nova de São Pedro",
    "Vila Nova de Tazem",
    "Vila Ruiva",
    "Vila Soeiro do Chão",
    "Vila Verde dos Francos",
    "Vilar",
    "Vilar de Amargo",
    "Vilar Maior",
    "Vilar Torpim",
    "Vilares",
    "Vimeiro",
    "Vinhó",
    "A dos Francos",
    "Alcobaça",
    "Alfeizerão",
    "Aljubarrota",
    "Alvaiázere",
    "Alvorninha",
    "Ansião",
    "Caranguejeira",
    "Castanheira de Pêra",
    "Cela",
    "Figueiró Dos Vinhos",
    "Foz do Arelho",
    "Louriçal",
    "Monte Real",
    "Nazaré",
    "Óbidos",
    "Pedrógão Grande",
    "Porto de Mós",
    "Salir de Matos",
    "São Martinho do Porto",
    "Serra de El-Rei",
    "Turquel",
    "Vestiaria",
    "Vidais",
    "A dos Cunhados",
    "Beato António",
    "Cacém",
    "Moscavide e Portela",
    "São João dos Montes",
    "Água de Pena",
    "Boaventura",
    "Camacha",
    "Câmara de Lobos",
    "Campanário",
    "Caniçal",
    "Caniço",
    "Curral das Freiras",
    "Estreito da Calheta",
    "Faial",
    "Fajã da Ovelha",
    "Nossa Senhora do Monte",
    "Porto Santo",
    "São Jorge",
    "Alter do Chão",
    "Avis",
    "Castelo de Vide",
    "Crato",
    "Fronteira",
    "Gavião",
    "Marvão",
    "Montargil",
    "Santo André",
    "Sousel",
    "Vale da Amoreira",
    "Água Longa",
    "Águas Santas",
    "Aguçadoura",
    "Alpendurada",
    "Argivai",
    "Árvore",
    "Aver-o-Mar",
    "Aves",
    "Azenha",
    "Baião",
    "Balazar",
    "Beiriz de Baixo",
    "Bougado",
    "Castelões de Cepeda",
    "Ermesinde",
    "Estela",
    "Fânzeres",
    "Figueiró",
    "Foz do Douro",
    "Frazão",
    "Grijó",
    "Guifões",
    "Leça da Palmeira",
    "Leça do Bailio",
    "Lustosa",
    "Marco de Canavezes",
    "Matosinhos",
    "Meinedo",
    "Melres",
    "Milheirós",
    "Mindelo",
    "Moreira",
    "Paços de Ferreira",
    "Pedrouços",
    "Perafita",
    "Perozinho",
    "Póvoa de Varzim",
    "Rebordões",
    "Rio Mau",
    "Santa Cruz do Bispo",
    "Santo Izidoro",
    "São Félix da Marinha",
    "São Mamede de Infesta",
    "São Miguel do Couto",
    "São Pedro da Cova",
    "São Romão do Coronado",
    "Sermonde",
    "Telões",
    "Vairão",
    "Valadares",
    "Vila Meã",
    "Vila Nova da Telha",
    "Vilar de Andorinho",
    "Vilar do Paraíso",
    "Vilarinho",
    "Alcanhões",
    "Alferrarede",
    "Alpiarça",
    "Amiães de Baixo",
    "Azinhaga",
    "Chamusca",
    "Constância",
    "Fátima",
    "Fazendas de Almeirim",
    "Ferreira do Zêzere",
    "Golegã",
    "Mação",
    "Montalvinho",
    "Ourém",
    "Paialvo",
    "Pego",
    "Pinheiro Grande",
    "Poceirão",
    "Pontével",
    "Santa Margarida da Coutada",
    "Santarém",
    "São Miguel de Rio Torto",
    "São Vicente do Paul",
    "Tramagal",
    "Vale de Figueira",
    "Vale de Santarém",
    "Vila Chã de Ourique",
    "Alcácer do Sal",
    "Arrentela",
    "Azeitão",
    "Charneca de Caparica",
    "Comporta",
    "Grândola",
    "Laranjeira",
    "Porto Covo",
    "Quinta Do Conde",
    "Rosairinho",
    "Santiago do Cacém",
    "Santo António da Charneca",
    "Sarilhos Pequenos",
    "Setúbal",
    "Sines",
    "Areosa",
    "Meadela",
    "Melgaço",
    "Monção",
    "Valença",
    "Valenza",
    "Vila Praia de Âncora",
    "Alijó",
    "Favaios",
    "Mesão Frio",
    "Mondim de Basto",
    "Montalegre",
    "Peso da Régua",
    "Ribeira de Pena",
    "Sabrosa",
    "Santa Marta de Penaguião",
    "Sobreira",
    "Valpaços",
    "Vila Pouca de Aguiar",
    "Abraveses",
    "Armamar",
    "Cabanas de Viriato",
    "Campo de Besteiros",
    "Canas de Senhorim",
    "Carregal do Sal",
    "Cinfães",
    "Ervedosa do Douro",
    "Moimenta da Beira",
    "Mortágua",
    "Oliveira de Frades",
    "Penalva do Castelo",
    "Resende",
    "Rio de Loba",
    "Santa Comba Dão",
    "São João da Pesqueira",
    "São João de Areias",
    "São Pedro do Sul",
    "Sátão",
    "Sernancelhe",
    "Tabuaço",
    "Vouzela"
];
*/

return [
    "Abóbada",
    "Abrantes",
    "Açores",
    "Aguada de Cima",
    "Agualva",
    "Aguçadoura",
    "Aguiar da Beira",
    "Alandroal",
    "Albergaria-a-Velha",
    "Albufeira",
    "Alcabideche",
    "Alcácer do Sal",
    "Alcains",
    "Alcanede",
    "Alcanena",
    "Alcobaça",
    "Alcochete",
    "Alcoentre",
    "Aldeia de Paio Pires",
    "Aldeia do Meio",
    "Aldeia dos Fernandes",
    "Alenquer",
    "Alfarelos",
    "Alfena",
    "Alfornelos",
    "Alfragide",
    "Algés",
    "Algoz",
    "Algueirão",
    "Alhandra",
    "Alhos Vedros",
    "Aljezur",
    "Aljustrel",
    "Almada",
    "Almancil",
    "Almargem",
    "Almeirim",
    "Almodôvar", // Corrected from Almodovar
    "Alpiarça",
    "Alportel",
    "Alqueidão da Serra",
    "Alter do Chão",
    "Altura",
    "Alvaiázere",
    "Alvarinhos",
    "Alvelos",
    "Alverca", // Often Alverca do Ribatejo, but Alverca alone exists
    "Amadora",
    "Amarante",
    "Amares",
    "Amiães de Cima",
    "Amor",
    "Amora",
    "Amoreira",
    "Amorim",
    "Anadia",
    "Anta",
    "Apúlia", // Corrected from Apulia
    "Arazede",
    "Arco da Calheta",
    "Arcos de Valdevez",
    "Arcozelo",
    "Arganil",
    "Argoncilhe",
    "Armação de Pêra",
    "Arouca",
    "Arraiolos",
    "Arrifana",
    "Arronches",
    "Arruda dos Vinhos",
    "Árvore", // Corrected from Arvore
    "Assumar",
    "Atalaia",
    "Atouguia da Baleia",
    "Avanca",
    "Aveiras de Cima",
    "Aveiro",
    "Avelar",
    "Avidos",
    "Avintes",
    "Azoia",
    "Azueira",
    "Azurém", // Corrected from Azurem
    "Baguim",
    "Baguim do Monte",
    "Baleia",
    "Baltar",
    "Barcarena",
    "Barcelos",
    "Barreiro",
    "Barrosas",
    "Basto", // Generic, part of other names typically
    "Batalha",
    "Beira", // Region, or part of place names
    "Beja",
    "Belas",
    "Belmonte",
    "Benfica", // Corrected from Bemfica
    "Benafim",
    "Benavente",
    "Benedita",
    "Bicesse",
    "Bico",
    "Boavista",
    "Bobadela",
    "Boliqueime",
    "Bombarral",
    "Borba",
    "Boticas",
    "Bouça", // Corrected from Bouca
    "Braga",
    "Bragança",
    "Brito",
    "Bucelas",
    "Buraca",
    "Cabanelas",
    "Cabeceiras de Basto",
    "Cabeço de Vide",
    "Cabecudos",
    "Cabrela",
    "Cacela",
    "Cacém",
    "Cacilhas",
    "Cadaval",
    "Caldas", // Generic, usually part of a full name like Caldas da Rainha
    "Caldas da Rainha",
    "Caldas das Taipas",
    "Caldas de São Jorge",
    "Caldas de Vizela",
    "Calvão",
    "Calvaria de Cima",
    "Camarate",
    "Caminha",
    "Campanário",
    "Câmpia", // Corrected from Campia
    "Campinho",
    "Campo",
    "Campo Maior",
    "Caneças",
    "Canedo",
    "Canelas",
    "Canhas",
    "Caniçal",
    "Caniço",
    "Canidelo",
    "Cano",
    "Cantanhede",
    "Caparica",
    "Caramulo",
    "Carapinheira",
    "Carcavelos",
    "Carnaxide",
    "Carrazedo",
    "Carregado",
    "Carriço",
    "Cartaxo",
    "Carvalhal",
    "Carvalho",
    "Carvalhosa",
    "Carvoeiro",
    "Casal",
    "Casal da Areia",
    "Cascais",
    "Castanheira do Ribatejo",
    "Castelejo",
    "Castelo",
    "Castelo Branco",
    "Castelo de Paiva",
    "Castro Daire",
    "Castro Marim",
    "Castro Verde",
    "Catraia de São Paio",
    "Cavaleiros",
    "Cavalões", // Corrected from Cavaloes
    "Caxias",
    "Ceira",
    "Celorico de Basto",
    "Cercal",
    "Cernache",
    "Cesar",
    "Chão de Couce",
    "Charneca", // Generic, often part of Charneca da Caparica
    "Chaves",
    "Cidade", // Generic, means "city"
    "Cinfães",
    "Coimbra",
    "Colares",
    "Colmeias",
    "Condeixa-a-Nova",
    "Constância", // Assuming "Constance" was a typo for this
    "Constância",
    "Corroios",
    "Cortegaça",
    "Costa da Caparica", // Corrected from Costa de Caparica
    "Costa de Lavos",
    "Covilhã",
    "Creixomil",
    "Cruz Quebrada",
    "Cuba",
    "Cucujães",
    "Dalvares",
    "Damaia",
    "Darque",
    "Dois Portos",
    "Dona Maria",
    "Dossãos", // Corrected from Dossaos
    "Eixo",
    "Elvas",
    "Encarnação",
    "Entroncamento",
    "Ericeira",
    "Ermidas", // Often Ermidas-Sado
    "Escapães",
    "Escoural",
    "Esmoriz",
    "Espinho",
    "Esposende",
    "Estarreja",
    "Estoi",
    "Estômbar",
    "Estoril",
    "Estremoz",
    "Évora",
    "Fafe",
    "Famões",
    "Fânzeres",
    "Fão",
    "Faro",
    "Feira", // Generic, often Santa Maria da Feira
    "Felgueiras",
    "Ferradosa",
    "Ferreira", // Generic
    "Ferreira do Alentejo",
    "Ferrel",
    "Ferro",
    "Fiães",
    "Figueira da Foz",
    "Figueira de Lorvão",
    "Figueiró dos Vinhos",
    "Fogueteiro",
    "Folgados",
    "Forte", // Generic, often Forte da Casa
    "Foz do Sousa",
    "Fradelos",
    "Freamunde",
    "Frielas",
    "Funchal",
    "Fundão",
    "Gafanha da Nazaré",
    "Galiza",
    "Gândara dos Olivais",
    "Gandra",
    "Garruchas",
    "Gemunde",
    "Godim",
    "Golegã",
    "Gondomar",
    "Gouveia",
    "Graça",
    "Gradil",
    "Grândola",
    "Granja",
    "Granja do Ulmeiro",
    "Grijó",
    "Guarda",
    "Guardizela",
    "Guia",
    "Guimarães",
    "Gulpilhares",
    "Igreja Nova",
    "Ílhavo",
    "Infesta", // Often São Mamede de Infesta
    "Joane",
    "Jovim",
    "Juncal",
    "Lagarinhos",
    "Lago",
    "Lagoa",
    "Lagoas",
    "Lagos",
    "Lajes", // Generic, often Lajes das Flores or Lajes do Pico
    "Lamego",
    "Landim",
    "Lavos",
    "Lavra",
    "Lavradio",
    "Leça da Palmeira",
    "Leça do Bailio",
    "Leiria",
    "Linda a Velha",
    "Linhaceira",
    "Linho", // Linhó is also common
    "Lisboa",
    "Lordelo",
    "Loulé",
    "Lourel de Baixo",
    "Loures",
    "Louriçal",
    "Lourosa",
    "Lousã",
    "Lousada",
    "Lousado",
    "Maçãs de Caminho",
    "Maceda",
    "Macedo de Cavaleiros",
    "Maceira",
    "Machico",
    "Macieira da Lixa",
    "Madeira",
    "Mafra",
    "Maia",
    "Malveira",
    "Malveira da Serra",
    "Mamouros",
    "Mangualde",
    "Manique de Baixo",
    "Manique do Intendente",
    "Marco", // Generic, often Marco de Canaveses
    "Marco de Canaveses",
    "Margaride", // (Felgueiras)
    "Marinha", // Generic, often Marinha Grande
    "Marinha Grande",
    "Marinhais",
    "Marteleira",
    "Martingança",
    "Massamá",
    "Massarelos",
    "Matosinhos",
    "Mealhada",
    "Mem Martins",
    "Mesão Frio",
    "Mexilhoeira Grande",
    "Milharado",
    "Milhazes",
    "Minde",
    "Mira",
    "Miranda do Corvo",
    "Miranda do Douro",
    "Mirandela",
    "Moçarria", // Corrected from Mocarria
    "Modivas",
    "Moita",
    "Monção",
    "Monchique",
    "Monforte",
    "Monsanto",
    "Monsaraz",
    "Montalvo",
    "Monte Estoril",
    "Montelavar",
    "Montemor-o-Novo",
    "Montemor-o-Velho",
    "Montes",
    "Montijo",
    "Moreira de Cónegos",
    "Mortágua",
    "Moscavide",
    "Moura",
    "Moure",
    "Mourisca do Vouga",
    "Mozelos",
    "Muro",
    "Murtede",
    "Murteira",
    "Nadadouro",
    "Negrelos",
    "Neiva",
    "Nelas",
    "Nespereira",
    "Nine",
    "Nisa",
    "Nogueira",
    "Nogueira da Regedoura",
    "Nogueira do Cravo",
    "Óbidos",
    "Odemira",
    "Odivelas",
    "Oeiras",
    "Oiã",
    "Olhão",
    "Olhos de Água",
    "Olivais",
    "Olival",
    "Oliveira", // Generic
    "Oliveira do Bairro",
    "Oliveira do Douro",
    "Oliveira do Hospital",
    "Ortiga",
    "Ota",
    "Ourém",
    "Ourique",
    "Outeiro",
    "Ovar",
    "Paço de Arcos",
    "Paderne",
    "Palhaça",
    "Palhais",
    "Palmeira",
    "Palmela",
    "Parada de Gonta",
    "Parada do Bispo",
    "Paraíso",
    "Parchal",
    "Pardilhó", // Corrected from Pardilho
    "Parede",
    "Paredes",
    "Paredes da Beira",
    "Paredes de Coura",
    "Pataias",
    "Paul", // Paúl is also seen
    "Pechão",
    "Pedreiras",
    "Pedroso", // Pedrógão is different
    "Pedrouços",
    "Pegões Velhos",
    "Penacova",
    "Penafiel",
    "Penedono",
    "Penela",
    "Penha Garcia",
    "Peniche",
    "Penteado",
    "Pereira",
    "Pêro Pinheiro",
    "Pevidém",
    "Piedade",
    "Pinhal",
    "Pinhal Novo",
    "Pinheiro",
    "Pinheiro da Bemposta",
    "Pinheiro de Ázere",
    "Poceirão",
    "Poço Barreto",
    "Poiares", // Often Vila Nova de Poiares
    "Polima",
    "Pombal",
    "Ponta", // Generic
    "Ponta Delgada",
    "Ponta do Sol",
    "Ponte", // Generic
    "Ponte da Barca",
    "Ponte de Lima",
    "Ponte de Sor",
    "Ponte de Vagos",
    "Pontével",
    "Pontinha",
    "Portalegre",
    "Portel",
    "Portela",
    "Portimão",
    "Porto",
    "Porto Alto",
    "Porto da Cruz",
    "Porto de Mós",
    "Porto Moniz",
    "Porto Salvo",
    "Póvoa", // Generic, often Póvoa de Varzim, etc.
    "Póvoa da Galega",
    "Póvoa de Lanhoso",
    "Póvoa de Santa Iria",
    "Póvoa de Santo Adrião",
    "Póvoa do Forno",
    "Prado",
    "Pragal",
    "Praia da Vitória",
    "Praia de Mira",
    "Praia do Almoxarife",
    "Praia do Carvoeiro",
    "Praia do Ribatejo",
    "Prazins", // (Guimarães)
    "Prime",
    "Proença-a-Nova",
    "Quarteira",
    "Queijas",
    "Queluz",
    "Queluz de Baixo",
    "Quinchães",
    "Quinta", // Generic
    "Quinta do Anjo",
    "Ramada",
    "Ramo",
    "Rana", // (São Domingos de Rana)
    "Real",
    "Rebordosa",
    "Recarei",
    "Redondo",
    "Regueira de Pontes",
    "Reguengo Grande",
    "Reguengos de Monsaraz",
    "Riachos",
    "Riba de Ave", // Riba d'Ave also common
    "Ribeira Brava",
    "Ribeira Grande",
    "Ribeirão",
    "Rinchoa",
    "Rio de Moinhos",
    "Rio de Mouro",
    "Rio Maior",
    "Rio Tinto",
    "Romariz",
    "Ronfe",
    "Roque", // Generic, São Roque
    "Roriz",
    "Runa",
    "Sabugal",
    "Sacavém",
    "Salreu",
    "Salto",
    "Salvaterra de Magos",
    "Samil",
    "Samora Correia",
    "Samouco",
    "Sandim",
    "Sanfins do Douro",
    "Sangalhos",
    "Sanguedo",
    "Santa Bárbara de Nexe",
    "Santa Catarina",
    "Santa Catarina da Serra",
    "Santa Clara-a-Velha",
    "Santa Comba Dão",
    "Santa Cruz",
    "Santa Iria de Azóia", // Corrected from Santa Iria da Azoia
    "Santa Marta", // Generic, often Santa Marta de Penaguião
    "Santa Marta de Penaguião",
    "Santana",
    "Santiago", // Generic, often Santiago do Cacém
    "Santiago da Guarda",
    "Santiago de Riba-Ul",
    "Santiago do Cacém",
    "Santo André",
    "Santo Antão do Tojal",
    "Santo António",
    "Santo António da Charneca",
    "Santo Tirso",
    "São Brás",
    "São Brás de Alportel",
    "São Domingos de Rana",
    "São Félix da Marinha",
    "São Francisco",
    "São João",
    "São João da Madeira",
    "São João da Talha",
    "São João das Lampas",
    "São João de Ver",
    "São João do Campo",
    "São João dos Montes",
    "São Julião do Tojal",
    "São Mamede de Infesta",
    "São Marcos",
    "São Pedro da Cadeira",
    "São Pedro do Estoril",
    "São Romão do Coronado",
    "São Roque",
    "São Vicente da Beira",
    "São Vicente de Lafões",
    "Sardoal",
    "Sarilhos Grandes",
    "Sátão",
    "Seia",
    "Seixal",
    "Sendim",
    "Senhora da Hora",
    "Seroa", // Sêroa
    "Serpa",
    "Serpins",
    "Sertã",
    "Sesimbra",
    "Sete Rios",
    "Sever do Vouga",
    "Silva",
    "Silvares",
    "Silveira",
    "Silves",
    "Sines",
    "Sintra",
    "Soalheira",
    "Sobrado",
    "Sobrado de Paiva",
    "Sobral de Monte Agraço",
    "Sobralinho",
    "Sobreda",
    "Sobreiro",
    "Sobrosa",
    "Soito",
    "Soure",
    "Souto da Carpalhosa",
    "Souzel", // Sousel is different
    "Sul", // Generic
    "Tabuaço",
    "Talaíde", // Corrected from Talaide
    "Tamel", // (São Veríssimo)
    "Tarouca",
    "Taveiro",
    "Tavira",
    "Teixoso",
    "Telhado",
    "Tercena",
    "Terena",
    "Tires",
    "Tocha",
    "Tomar",
    "Tondela",
    "Torre da Marinha",
    "Torre de Moncorvo",
    "Torres Novas",
    "Torres Vedras",
    "Touguinha",
    "Tourais",
    "Trafaria",
    "Trancoso",
    "Trancoso de Baixo", // Unsure if this is distinct from Trancoso, possibly a local area. Kept as is.
    "Travanca",
    "Treixedo",
    "Trofa",
    "Tunes",
    "Turcifal",
    "Vagos",
    "Valado dos Frades", // Corrected from Valado de Frades
    "Valbom",
    "Vale", // Generic
    "Vale da Pinta",
    "Vale de Açor",
    "Vale de Cambra",
    "Válega",
    "Valença",
    "Valongo",
    "Valverde",
    "Várzea do Douro",
    "Venda do Pinheiro",
    "Vendas Novas",
    "Vermelha",
    "Vermoil",
    "Vialonga",
    "Viana do Alentejo",
    "Viana do Castelo",
    "Vidago",
    "Vidigueira",
    "Vieira de Leiria",
    "Vieira do Minho",
    "Vila Alva",
    "Vila Boa de Quires",
    "Vila Chã",
    "Vila Chã de Ourique",
    "Vila Baleira", // Official name for Vila de Porto Santo
    "Vila do Bispo",
    "Vila do Conde",
    "Vila Franca de Xira",
    "Vila Franca do Rosário",
    "Vila Nogueira de Azeitão",
    "Vila Nova", // Generic
    "Vila Nova da Barquinha",
    "Vila Nova de Cerveira",
    "Vila Nova de Famalicão",
    "Vila Nova de Gaia",
    "Vila Nova de Paiva",
    "Vila Praia de Âncora",
    "Vila Real",
    "Vila Verde",
    "Vilar de Perdizes",
    "Vilar do Paraíso",
    "Vilar do Pinheiro",
    "Vilar Formoso",
    "Vilarinho das Paranheiras",
    "Vilarinho de Arcos",
    "Vilarinho do Bairro",
    "Vilela",
    "Vimieiro",
    "Vinhais",
    "Viseu",
    "Vizela",
    "Zambujal",
    "Zibreira",
    "Águeda",
    "Aradas",
    "Arcos",
    "Beduído", // Beduído e Veiros
    "Branca",
    "Cortegaça",
    "Cucujães",
    "Esgueira",
    "Espargo",
    "Fiães",
    "Gafanha da Encarnação",
    "Gafanha da Nazaré",
    "Ílhavo",
    "Lamas",
    "Lobão",
    "Luso",
    "Macieira de Cambra",
    "Milheirós de Poiares",
    "Mosteirô", // Mosteiró
    "Murtosa",
    "Oiã",
    "Oliveira de Azeméis", // Correcting the second instance too
    "Oliveira de Azeméis",
    "Oliveirinha",
    "Paços de Brandão",
    "Pampilhosa do Botão",
    "Pardilhó",
    "Rio Meão",
    "Sanfins",
    "Santa Maria da Feira",
    "São João",
    "São João da Madeira",
    "São João de Ver",
    "São Roque",
    "Silvalde",
    "Souto",
    "Válega",
    "Vila Chã",
    "Água de Pau",
    "Angra do Heroísmo",
    "Angústias", // (Horta)
    "Arrifes",
    "Biscoitos",
    "Cabouco",
    "Cais do Pico",
    "Calheta",
    "Calheta de São Jorge",
    "Corvo",
    "Fajã de Baixo",
    "Fenais da Ajuda",
    "Fenais da Luz",
    "Feteira",
    "Fonte Bastardo",
    "Furnas",
    "Horta",
    "Lajes das Flores",
    "Lajes do Pico",
    "Madalena",
    "Mosteiros",
    "Nordeste",
    "Ponta Garça",
    "Porto Judeu",
    "Porto Martins",
    "Povoação",
    "Praia da Vitória",
    "Rabo de Peixe",
    "Relva",
    "Ribeira Seca",
    "Ribeirinha",
    "Rosto de Cão", // (Livramento or São Roque)
    "Santa Bárbara",
    "Santa Cruz da Graciosa",
    "Santa Cruz das Flores",
    "São Bartolomeu", // (de Regatos, Angra do Heroísmo)
    "São Mateus", // (da Calheta, etc.)
    "São Roque do Pico",
    "São Sebastião",
    "São Vicente",
    "Senhora do Rosário", // (Lagoa)
    "Velas",
    "Vila do Porto",
    "Vila Franca do Campo",
    "Aldeia Nova de São Bento",
    "Almodôvar",
    "Almograve",
    "Alvito",
    "Barrancos",
    "Beringel",
    "Boavista dos Pinheiros",
    "Cabeça Gorda",
    "Castro Verde",
    "Mértola",
    "Minas de São Domingos",
    "Neves",
    "Penedo Gordo",
    "Salvada",
    "São Luis", // São Luís
    "São Teotónio",
    "Vila Nova de Milfontes",
    "Zambujeira do Mar",
    "Adaúfe",
    "Apúlia",
    "Apúlia e Fão",
    "Arões", // (São Romão)
    "Aveleda",
    "Barqueiros",
    "Caldelas", // (Amares or Guimarães)
    "Calendário",
    "Candoso",
    "Chavão",
    "Cristelo",
    "Esporões",
    "Faria",
    "Ferreiros",
    "Frossos",
    "Galegos",
    "Gondizalves",
    "Gueral",
    "Guimarães", // Repeated, already up
    "Guisande",
    "Macieira de Rates",
    "Marinhas",
    "Mariz",
    "Merelim", // (São Paio, São Pedro, etc.)
    "Negreiros",
    "Perelhal",
    "Póvoa de Lanhoso",
    "Refojos de Basto",
    "Rendufe",
    "Ribeirão", // Repeated, already up
    "Sande",
    "Selho", // (São Cristóvão, São Jorge, etc.)
    "Semelhe",
    "Serzedelo",
    "Serzedo",
    "Tebosa",
    "Terras de Bouro",
    "Urgeses",
    "Várzea",
    "Vila Cova",
    "Vila Frescainha", // (São Martinho or São Pedro)
    "Vila Nova de Famalicão", // Repeated
    "Vila Seca",
    "Vilaça",
    "Vilar de Figos",
    "Alfândega da Fé",
    "Belver",
    "Bragança", // Municipality already covered by "Bragança"
    "Carrazeda de Ansiães", // Standardized spelling
    "Carrazeda de Ansiães", // Repeated
    "Freixo de Espada à Cinta",
    "Mogadouro",
    "Vila Flor",
    "Vimioso",
    "Aldeia de Joanes",
    "Covilhã", // Repeated
    "Fundão", // Repeated
    "Idanha-a-Nova",
    "Oleiros",
    "Penamacor",
    "Proença-a-Nova", // Repeated
    "Sertã", // Repeated
    "Vila de Rei",
    "Vila Velha de Ródão",
    "Alhadas",
    "Ançã",
    "Assafarge", // Assafarge e Antanhol
    "Buarcos", // Buarcos e São Julião
    "Figueira da Foz", // Repeated
    "Góis",
    "Lorvão",
    "Lousã", // Repeated
    "Oliveira do Mondego", // Oliveira do Mondego e Travanca do Mondego
    "Pampilhosa da Serra",
    "Santa Clara", // Santa Clara e Castelo Viegas (Coimbra)
    "Santo António dos Olivais",
    "São Pedro de Alva", // São Pedro de Alva e São Francisco de Alva
    "Soure", // Repeated
    "Tábua",
    "Tavarede",
    "Vila Nova de Poiares",
    "Évora", // Repeated
    "Mora",
    "Mourão",
    "Vila Viçosa",
    "Alcantarilha", // Alcantarilha e Pêra
    "Alcoutim",
    "Alvor",
    "Armação de Pêra", // Repeated
    "Bensafrim", // Bensafrim e Barão de São João
    "Cabanas de Tavira",
    "Conceição", // Conceição e Estoi
    "Estói", // Already part of Conceição e Estoi
    "Estômbar", // Estômbar e Parchal
    "Ferragudo",
    "Ferreiras",
    "Fuzeta", // Fuseta
    "Laranjeiro", // Laranjeiro e Feijó
    "Loulé", // Repeated
    "Luz", // (de Tavira or Lagos)
    "Manta Rota",
    "Marmelete",
    "Moncarapacho", // Moncarapacho e Fuseta
    "Monte Gordo",
    "Olhão", // Repeated
    "Olhos de Água", // Repeated
    "Pêra", // Already part of Alcantarilha e Pêra
    "Porches",
    "Portimão", // Repeated
    "Sagres",
    "Santa Bárbara de Nexe", // Repeated
    "Santa Luzia",
    "São Bartolomeu de Messines",
    "São Brás de Alportel", // Repeated
    "São Marcos da Serra",
    "Senhora da Luz", // (Luz - Lagos)
    "Tavira", // Repeated
    "Vila Nova de Cacela",
    "Vila Real de Santo António",
    "Vilamoura",
    "Abrigada",
    "Açores", // Repeated
    "Adão",
    "Águas Belas",
    "Aguiar da Beira", // Repeated
    "Ajuda", // (Lisboa or Peniche)
    "Albardo",
    "Alcântara", // (Lisboa)
    "Aldeia da Ponte",
    "Aldeia da Ribeira", // Aldeia da Ribeira, Vilar Maior e Badamalos
    "Aldeia de Santo António",
    "Aldeia do Bispo", // (Guarda or Penamacor or Sabugal)
    "Aldeia Galega da Merceana", // Aldeia Galega da Merceana e Aldeia Gavinha
    "Aldeia Gavinha", // Already part of above
    "Aldeia Nova (Miranda do Douro)", // Kept specificity
    "Aldeia Velha",
    "Aldeia Viçosa",
    "Aldeias",
    "Alfaiates",
    "Algés", // Algés, Linda-a-Velha e Cruz Quebrada-Dafundo
    "Algodres", // Algodres, Vale de Afonsinho e Vilar de Amargo
    "Alguber",
    "Algueirão", // Algueirão-Mem Martins
    "Algueirão-Mem Martins",
    "Almargem do Bispo", // Almargem do Bispo, Pêro Pinheiro e Montelavar
    "Almeida",
    "Almendra",
    "Almofala", // Almofala e Escarigo
    "Alto do Pina", // (Lisboa - former) Now Areeiro or Beato
    "Alvalade", // (Lisboa or Santiago do Cacém)
    "Alvendre",
    "Alverca da Beira", // Alverca da Beira/Bouça Cova
    "Alverca do Ribatejo", // Alverca do Ribatejo e Sobralinho
    "Alvoco da Serra",
    "Ameixoeira", // (Lisboa)
    "Anjos", // (Lisboa - former) Now Arroios
    "Apelação", // (Loures)
    "Arranhó",
    "Arruda dos Vinhos", // Repeated
    "Aveiras de Baixo",
    "Avelãs da Ribeira",
    "Aveloso",
    "Azambuja",
    "Azambuja", // Repeated
    "Azenhas do Mar",
    "Azevo", // Azevo e Sobral de Pires
    "Baraçal",
    "Barreira", // (Leiria or Mação)
    "Beato", // (Lisboa)
    "Bendada",
    "Benespera",
    "Benfica", // Repeated
    "Bismula",
    "Bouça Cova", // Already with Alverca da Beira
    "Brandoa", // Encosta do Sol (Amadora)
    "Cabanas de Torres",
    "Cabeça", // (Seia)
    "Cachoeiras", // (Vila Franca de Xira)
    "Cadafais", // (Alenquer)
    "Cadafaz", // Cadafaz e Colmeal (Góis)
    "Calhandriz",
    "Campelos", // Campelos e Outeiro da Cabeça
    "Campo Grande", // (Lisboa)
    "Campolide", // (Lisboa)
    "Caneças", // Ramada e Caneças
    "Carapito",
    "Cardosas",
    "Carmões",
    "Carnicães",
    "Carnide", // (Lisboa or Pombal)
    "Carnota",
    "Carragozela", // Carragozela e Várzea de Meruge
    "Carrapichana",
    "Carvoeira", // (Mafra or Torres Vedras)
    "Casal de Cambra",
    "Casal de Cinza",
    "Casal Vasco",
    "Casas do Soeiro",
    "Castanheira", // Castanheira de Pêra e Coentral or Castanheira do Ribatejo e Cachoeiras
    "Casteição",
    "Casteleiro",
    "Castelo", // (Lisboa - São Jorge) or other Castelo.
    "Castelo Bom",
    "Castelo Melhor",
    "Castelo Rodrigo",
    "Cativelos",
    "Cavadoude",
    "Cedovim",
    "Celorico da Beira",
    "Cerdeira", // Cerdeira e Moura da Serra
    "Cerejo", // Cerejo ou Ervas Tenras
    "Chãs", // (Vila Nova de Foz Côa)
    "Cheleiros",
    "Codesseiro",
    "Cogula",
    "Coração de Jesus", // (Lisboa - former) Now Santo António
    "Coriscada",
    "Cortiçada",
    "Cortiçô", // Cortiçô da Serra, Vide Entre Vinhas e Salgueirais
    "Cortiçô da Serra", // Part of above
    "Coruche", // (Aguiar da Beira or Coruche town)
    "Corujeira", // Corujeira e Trinta
    "Cótimos",
    "Cruz Quebrada-Dafundo", // Part of Algés, Linda-a-Velha e Cruz Quebrada-Dafundo
    "Custóias", // Custóias, Leça do Balio e Guifões
    "Dornelas", // (Aguiar da Beira or Boticas or Sever do Vouga)
    "Eirado",
    "Encarnação", // (Lisboa or Mafra)
    "Enxara do Bispo", // Enxara do Bispo, Gradil e Vila Franca do Rosário
    "Ervas Tenras", // Already with Cerejo
    "Ervedosa", // (Douro or Vinhais)
    "Escalhão",
    "Faia", // (Guarda or Sernancelhe)
    "Falagueira", // Falagueira-Venda Nova
    "Famalicão", // (da Serra or Nazaré or Vila Nova de Famalicão)
    "Famões", // Pontinha e Famões
    "Fanhões",
    "Fernão Joanes",
    "Figueira de Castelo Rodrigo",
    "Figueira do Guincho",
    "Figueiró da Granja",
    "Figueiró da Serra", // Figueiró da Serra e Freixo da Serra
    "Figueiros",
    "Fóios",
    "Folgosinho",
    "Folhadosa",
    "Fontanelas", // São João das Lampas e Terrugem
    "Fonte Longa",
    "Forninhos",
    "Forno Telheiro",
    "Fornos de Algodres",
    "Forte da Casa", // Póvoa de Santa Iria e Forte da Casa
    "Freches", // Freches e Torres
    "Freineda",
    "Freiria",
    "Freixeda do Torrão", // Freixeda do Torrão, Quintã de Pêro Martins e Penha de Águia
    "Freixedas",
    "Freixo", // (de Numão or Espada à Cinta or Serra)
    "Freixo de Numão", // Freixo de Numão ou Ribacôa
    "Gagos", // (Guarda)
    "Girabolhos",
    "Gonçalo",
    "Gonçalo Bocas",
    "Graça", // (Lisboa or Pedrógão Grande)
    "Gradiz", // Gradiz e Enxara do Bispo (former)
    "Guilheiro",
    "Infias", // (Fornos de Algodres or Vizela)
    "Jarmelo São Miguel",
    "Jarmelo São Pedro",
    "João Antão",
    "Junça", // Junça e Naves (Almeida)
    "Juncais", // Juncais, Vila Ruiva e Vila Soeiro do Chão
    "Lajeosa", // Lajeosa do Mondego
    "Lajeosa do Mondego",
    "Lamegal",
    "Lameiras",
    "Lapa", // (Cartaxo or Lisboa)
    "Lapa dos Dinheiros",
    "Leomil", // (Almeida or Moimenta da Beira)
    "Linda-a-Velha", // Part of Algés, Linda-a-Velha e Cruz Quebrada-Dafundo
    "Linhares", // (Celorico da Beira or Paredes de Coura)
    "Longroiva",
    "Loriga",
    "Lourinhã", // Lourinhã e Atalaia
    "Lumiar", // (Lisboa)
    "Maçainhas", // (Belmonte or Guarda)
    "Maçal do Chão",
    "Maçussa", // Azambuja or Mação (??) - Unclear, kept.
    "Malcata",
    "Malhada Sorda",
    "Malpartida", // Malpartida e Vale de Coelha
    "Mangualde da Serra",
    "Manigoto",
    "Manteigas",
    "Manteigas (São Pedro)", // Manteigas (Santa Maria, São Pedro e Sameiro)
    "Marialva",
    "Marmeleiro", // (Guarda or Sertã)
    "Mártires", // (Lisboa - former) Now Santa Maria Maior
    "Marvila", // (Lisboa or Santarém)
    "Massamá", // Massamá e Monte Abraão
    "Mata de Lobos",
    "Matacães",
    "Matança",
    "Maxial", // Maxial e Monte Redondo
    "Meca",
    "Mêda", // Mêda, Outeiro de Gatos e Fonte Longa
    "Meios",
    "Melo",
    "Mercês", // (Lisboa - former) Now Misericórdia or Sintra (Rio de Mouro)
    "Mesquitela",
    "Mina", // Mina de Água (Amadora)
    "Minhocal",
    "Mira-Sintra",
    "Miragaia", // (Porto or Lourinhã)
    "Miuzela", // Miuzela e Porto de Ovelha
    "Mizarela", // Mizarela, Pêro Soares e Vila Soeiro
    "Moimenta da Serra", // Moimenta da Serra e Vinhó
    "Moimentinha",
    "Moita dos Ferreiros",
    "Moledo", // (Caminha or Lourinhã)
    "Monte Abraão", // Massamá e Monte Abraão
    "Monte Redondo", // (Leiria or Torres Vedras)
    "Moreira de Rei",
    "Mós", // (Bragança, Torre de Moncorvo or Vila Verde)
    "Murça", // (Vila Nova de Foz Côa)
    "Muxagata", // (Fornos de Algodres or Vila Nova de Foz Côa)
    "Nabais",
    "Nave", // (Sabugal or Almeida - Nave de Haver)
    "Nave de Haver",
    "Nossa Senhora de Fátima", // (Lisboa - former) Now Avenidas Novas
    "Numão",
    "Odivelas", // Repeated
    "Oeiras e São Julião da Barra", // Oeiras e São Julião da Barra, Paço de Arcos e Caxias
    "Olhalvo",
    "Olival Basto", // Corrected. Póvoa de Santo Adrião e Olival Basto
    "Olival Basto", // Repeated
    "Outeiro da Cabeça", // Campelos e Outeiro da Cabeça
    "Outeiro de Gatos", // Mêda, Outeiro de Gatos e Fonte Longa
    "Paço de Arcos", // Part of Oeiras e S.J.Barra, P.Arcos, Caxias
    "Paços da Serra",
    "Painho",
    "Pala", // (Mortágua or Pinhel)
    "Panoias de Cima",
    "Parada", // (Alfândega da Fé, Almeida, Arcos de Valdevez, Bragança, Carregal do Sal, Paredes de Coura, Vila do Conde)
    "Paranhos", // (Porto or Seia)
    "Pega",
    "Pena", // (Lisboa - former) Now Arroios
    "Pena Lobo",
    "Pena Verde",
    "Penha de Águia", // Part of Freixeda do Torrão, Quintã de Pêro Martins e Penha de Águia
    "Penha de França", // (Lisboa)
    "Pêra do Moço",
    "Peral",
    "Pereiro", // (Alcoutim, Mação, Pinhel, Tabuaço)
    "Pereiro de Palhacana",
    "Pêro Moniz",
    "Peva", // Peva e Segões
    "Pinhanços",
    "Pinhel",
    "Pínzio",
    "Poço do Canto",
    "Pomares", // (Arganil or Pinhel)
    "Ponte do Rol",
    "Porto da Carne",
    "Pousada", // (Guarda)
    "Pousafoles do Bispo", // Pousafoles do Bispo, Pena Lobo e Lomba
    "Póvoa de Santa Iria", // Póvoa de Santa Iria e Forte da Casa
    "Póvoa de Santo Adrião", // Póvoa de Santo Adrião e Olival Basto
    "Póvoa do Concelho",
    "Prados", // (Celorico da Beira)
    "Prazeres", // (Lisboa or Calheta - Madeira)
    "Prior Velho", // Sacavém e Prior Velho
    "Prova", // Prova e Casteição
    "Quadrazais",
    "Queijas", // Part of Carnaxide e Queijas
    "Queiriz",
    "Quintã de Pêro Martins", // Part of Freixeda do Torrão, Quintã de Pêro Martins e Penha de Águia
    "Quintas de São Bartolomeu",
    "Rabaçal", // (Mêda or Penela)
    "Ramalhal",
    "Ramela",
    "Ranhados", // (Mêda or Viseu)
    "Rapa", // Rapa e Cadafaz
    "Rapoula do Côa",
    "Ratoeira",
    "Reboleira", // Venteira (Amadora)
    "Reboleiro",
    "Rebolosa",
    "Reigada",
    "Rendo",
    "Ribafria", // Ribafria e Pereiro de Palhacana
    "Ribamar", // (Lourinhã or Santo Isidoro - Mafra)
    "Ribamondego",
    "Ribeira dos Carinhos",
    "Rio de Mel",
    "Rio Torto", // Rio Torto e Carvalhal Meão (Gouveia)
    "Rochoso", // Rochoso e Monte Margarida
    "Ruvina",
    "Sabugueiro", // (Arraiolos or Seia)
    "Sacavém", // Sacavém e Prior Velho
    "Sacramento", // (Lisboa - former) Now Santa Maria Maior
    "Safurdão", // Safurdão e Matas de Minas
    "Salgueirais", // Part of Cortiçô da Serra, Vide Entre Vinhas e Salgueirais
    "Sameice",
    "Sameiro", // Manteigas (Santa Maria, São Pedro e Sameiro)
    "Sandomil",
    "Santa Comba", // (Ponte de Lima, Seia, Vila Nova de Foz Côa)
    "Santa Engrácia", // (Lisboa - former) Now São Vicente
    "Santa Eufémia", // (Guarda, Leiria, Penela, Pinhel)
    "Santa Eulália", // (Arouca, Elvas, Seia, Vizela)
    "Santa Iria de Azóia", // Santa Iria de Azoia, São João da Talha e Bobadela
    "Santa Iria de Azóia", // Repeated
    "Santa Isabel", // (Lisboa - former) Now Campo de Ourique or Santo António
    "Santa Justa", // (Lisboa - former) Now Santa Maria Maior
    "Santa Maria", // (Bragança, Celorico da Beira, Covilhã, Estremoz, Manteigas, Odemira, Serpa, Tavira, Torres Novas)
    "Santa Maria de Belém", // Belém (Lisboa)
    "Santa Maria do Castelo e São Miguel", // (Torres Vedras)
    "Santa Maria dos Olivais", // Olivais (Lisboa)
    "Santa Maria e São Miguel", // (Sintra)
    "Santa Marinha", // (Seia, Vila Nova de Gaia, Zêzere)
    "Santana da Azinha",
    "Santiago dos Velhos",
    "Santo Antão do Tojal", // Santo Antão do Tojal e São Julião do Tojal
    "Santo António dos Cavaleiros", // Santo António dos Cavaleiros e Frielas
    "Santo Condestável", // (Lisboa - former) Now Campo de Ourique
    "Santo Estêvão", // (Benavente, Chaves, Estremoz, Lisboa, Sabugal, Tavira)
    "Santo Estêvão das Galés",
    "Santo Isidoro", // (Mafra or Marco de Canaveses)
    "Santo Quintino",
    "Santos-o-Velho", // (Lisboa - former) Now Estrela
    "São Bartolomeu dos Galegos", // São Bartolomeu dos Galegos e Moledo
    "São Brás", // (Amadora or various others with 'de')
    "São Cristóvão e São Lourenço", // (Lisboa - former) Now Santa Maria Maior
    "São Domingos de Benfica", // (Lisboa)
    "São Domingos de Rana", // Repeated
    "São Francisco Xavier", // (Lisboa - former) Now Belém
    "São João da Talha", // Part of Santa Iria de Azoia, São João da Talha e Bobadela
    "São João das Lampas", // São João das Lampas e Terrugem
    "São João de Brito", // (Lisboa - former) Now Alvalade
    "São João de Deus", // (Lisboa - former) Now Areeiro
    "São João dos Montes", // Alhandra, São João dos Montes e Calhandriz
    "São Jorge de Arroios", // (Lisboa - former) Now Arroios
    "São José", // (Lisboa - former) Now Santo António
    "São Julião", // (Lisboa - former, Portalegre, Santarém, Setúbal, Valença)
    "São Julião do Tojal", // Part of Santo Antão do Tojal e São Julião do Tojal
    "São Mamede", // (Lisboa - former, Batalha, Évora, Santarém)
    "São Marcos", // (Cacém, Silves)
    "São Martinho", // (Alcácer do Sal, Castelo Branco, Covilhã, Funchal, Guarda, Santarém, Seia, Sintra)
    "São Miguel", // (Guarda, Lisboa - Alfama, Penela, Sintra, Vila Franca do Campo)
    "São Miguel da Guarda",
    "São Miguel de Alcainça",
    "São Nicolau", // (Lisboa - former or Marco de Canaveses or Santarém or Porto)
    "São Paio", // (Arcos de Valdevez, Gouveia, Guimarães, Melgaço)
    "São Paulo", // (Lisboa - former) Now Misericórdia
    "São Pedro", // Many places, e.g. Manteigas (São Pedro)
    "São Pedro da Cadeira",
    "São Pedro de Penaferrim", // (Sintra)
    "São Pedro de Rio Seco",
    "São Romão", // (Armamar, Seia, Vila Viçosa)
    "São Sebastião da Pedreira", // (Lisboa - former) Now Avenidas Novas
    "São Vicente de Fora", // São Vicente (Lisboa)
    "Sapataria",
    "Sazes da Beira",
    "Sé", // Generic, "Cathedral", often refers to a specific freguesia in cities like Braga, Funchal, Guarda, Lisboa, Porto.
    "Sebadelhe", // (Vila Nova de Foz Côa)
    "Sebadelhe da Serra",
    "Seixas", // (Caminha)
    "Seixo do Côa",
    "Sequeira",
    "Sequeiros", // (Aguiar da Beira or Viseu)
    "Sintra", // Repeated
    "Sobral da Abelheira",
    "Sobral da Serra",
    "Sobral de Monte Agraço", // Repeated
    "Sobral Pichorro", // Sobral Pichorro e Fuinhas
    "Socorro", // (Lisboa - former) Now Santa Maria Maior
    "Sortelha",
    "Souro Pires",
    "Souto de Aguiar da Beira", // Souto de Aguiar da Beira e Valverde
    "Souto Maior", // (Sabrosa or Trancoso)
    "Tamanhos",
    "Teixeira", // (Arganil or Baião or Seia)
    "Terrenho",
    "Terrugem", // (Elvas or Sintra - São João das Lampas e Terrugem)
    "Torre do Terrenho", // Torre do Terrenho e Sebadelhe da Serra (former)
    "Torres", // (Trancoso - Freches e Torres)
    "Torrozelo", // Torrozelo e Folhadosa
    "Touça",
    "Travancinha",
    "Triana", // (Alenquer)
    "Trinta", // Corujeira e Trinta
    "Unhos", // Camarate, Unhos e Apelação
    "Valdujo",
    "Vale da Mula",
    "Vale de Amoreira", // (Moita or Manteigas)
    "Vale de Azares",
    "Vale de Espinho",
    "Vale de Estrela",
    "Vale do Paraíso", // (Azambuja)
    "Vale do Seixo",
    "Vale Flor", // Vale Flor, Carvalhal de Estanho e Almofala (former)
    "Valezim",
    "Valhelhas",
    "Várzea de Meruge", // Part of Carragozela e Várzea de Meruge
    "Vascoveiro",
    "Vela", // (Guarda)
    "Velosa",
    "Venda Nova", // Falagueira-Venda Nova
    "Venteira", // (Amadora)
    "Ventosa", // (Alenquer, Torres Vedras, Vieira do Minho)
    "Vermiosa",
    "Vide", // Vide e Cabeça
    "Vide Entre Vinhas", // Part of Cortiçô da Serra, Vide Entre Vinhas e Salgueirais
    "Videmonte",
    "Vila Boa", // (Mirandela or Sabugal)
    "Vila Boa do Mondego",
    "Vila Cortês da Serra",
    "Vila Cortês do Mondego",
    "Vila Cova à Coelheira", // (Seia or Vila Nova de Paiva)
    "Vila do Touro",
    "Vila Fernando", // (Elvas or Guarda)
    "Vila Franca da Serra",
    "Vila Franca das Naves",
    "Vila Franca do Deão",
    "Vila Franca do Rosário", // Part of Enxara do Bispo, Gradil e Vila Franca do Rosário
    "Vila Garcia", // (Guarda or Trancoso)
    "Vila Nova da Rainha", // (Azambuja or Tondela)
    "Vila Nova de Foz Côa",
    "Vila Nova de São Pedro",
    "Vila Nova de Tazem",
    "Vila Ruiva", // (Cuba, Fornos de Algodres - Juncais, Vila Ruiva e Vila Soeiro do Chão)
    "Vila Soeiro do Chão", // Part of Juncais, Vila Ruiva e Vila Soeiro do Chão
    "Vila Verde dos Francos",
    "Vilar", // (Boticas, Cadaval, Moimenta da Beira, Terras de Bouro, Vila do Conde)
    "Vilar de Amargo", // Algodres, Vale de Afonsinho e Vilar de Amargo
    "Vilar Maior",
    "Vilar Torpim",
    "Vilares", // (Trancoso or Murça)
    "Vimeiro", // (Alcobaça or Lourinhã)
    "Vinhó", // Moimenta da Serra e Vinhó
    "A dos Francos",
    "Alcobaça", // Repeated
    "Alfeizerão",
    "Aljubarrota", // Aljubarrota (São Vicente e Prazeres)
    "Alvaiázere", // Repeated
    "Alvorninha",
    "Ansião",
    "Caranguejeira",
    "Castanheira de Pêra", // Castanheira de Pêra e Coentral
    "Cela", // (Alcobaça)
    "Figueiró dos Vinhos", // Repeated
    "Foz do Arelho",
    "Louriçal", // Repeated
    "Monte Real", // Monte Real e Carvide
    "Nazaré",
    "Óbidos", // Repeated
    "Pedrógão Grande",
    "Porto de Mós", // Porto de Mós - São João Batista e São Pedro
    "Salir de Matos",
    "São Martinho do Porto",
    "Serra de El-Rei",
    "Turquel",
    "Vestiaria",
    "Vidais",
    "A dos Cunhados", // A dos Cunhados e Maceira
    "Beato António", // Beato (Lisboa) - probably same as "Beato" earlier.
    "Cacém", // Cacém e São Marcos
    "Moscavide e Portela",
    "São João dos Montes", // Repeated
    "Água de Pena",
    "Boaventura",
    "Camacha",
    "Câmara de Lobos",
    "Campanário", // Repeated
    "Caniçal", // Repeated
    "Caniço", // Repeated
    "Curral das Freiras",
    "Estreito da Calheta",
    "Faial", // (Madeira or Açores)
    "Fajã da Ovelha",
    "Nossa Senhora do Monte", // (Funchal)
    "Porto Santo",
    "São Jorge", // (Madeira or Açores)
    "Alter do Chão", // Repeated
    "Avis",
    "Castelo de Vide",
    "Crato", // Crato e Mártires, Flor da Rosa e Vale do Peso
    "Fronteira",
    "Gavião", // Gavião e Belver
    "Marvão",
    "Montargil",
    "Santo André", // (Portalegre, Santiago do Cacém, etc.)
    "Sousel",
    "Vale da Amoreira", // (Fronteira or Moita)
    "Água Longa",
    "Águas Santas", // (Maia)
    "Aguçadoura", // Aguçadoura e Navais
    "Alpendurada", // Alpendorada, Várzea e Torrão
    "Argivai", // Póvoa de Varzim, Beiriz e Argivai
    "Árvore", // Repeated
    "Aver-o-Mar", // Aver-o-Mar, Amorim e Terroso
    "Aves", // (Vila das Aves)
    "Azenha", // (Porto) - Unclear, possibly local name.
    "Baião",
    "Balazar", // (Póvoa de Varzim)
    "Beiriz de Baixo", // Póvoa de Varzim, Beiriz e Argivai
    "Bougado", // Bougado (São Martinho e Santiago)
    "Castelões de Cepeda", // Paredes (freguesia)
    "Ermesinde",
    "Estela",
    "Fânzeres", // Fânzeres e São Pedro da Cova
    "Figueiró", // (Amarante or Paços de Ferreira)
    "Foz do Douro", // Aldoar, Foz do Douro e Nevogilde
    "Frazão", // Frazão Arreigada
    "Grijó", // Grijó e Sermonde
    "Guifões", // Custóias, Leça do Balio e Guifões
    "Leça da Palmeira", // Matosinhos e Leça da Palmeira
    "Leça do Bailio", // Custóias, Leça do Balio e Guifões
    "Lustosa", // Lustosa e Barrosas (Santo Estêvão)
    "Marco de Canaveses", // Repeated
    "Matosinhos", // Matosinhos e Leça da Palmeira
    "Meinedo",
    "Melres", // Melres e Medas
    "Milheirós", // (Maia)
    "Mindelo",
    "Moreira", // (Maia)
    "Paços de Ferreira",
    "Pedrouços", // Repeated
    "Perafita", // Perafita, Lavra e Santa Cruz do Bispo
    "Perozinho",
    "Póvoa de Varzim",
    "Rebordões", // (Santo Tirso)
    "Rio Mau", // Rio Mau e Arcos (Vila do Conde)
    "Santa Cruz do Bispo", // Perafita, Lavra e Santa Cruz do Bispo
    "Santo Izidoro", // (Santo Isidoro - Marco de Canaveses)
    "São Félix da Marinha", // Repeated
    "São Mamede de Infesta", // São Mamede de Infesta e Senhora da Hora
    "São Miguel do Couto",
    "São Pedro da Cova", // Fânzeres e São Pedro da Cova
    "São Romão do Coronado", // Coronado (São Romão e São Mamede)
    "Sermonde", // Grijó e Sermonde
    "Telões", // (Amarante or Vila Pouca de Aguiar)
    "Vairão", // Fornelo e Vairão
    "Valadares", // (Baião, Monção, Vila Nova de Gaia)
    "Vila Meã", // (Amarante)
    "Vila Nova da Telha",
    "Vilar de Andorinho",
    "Vilar do Paraíso", // Mafamude e Vilar do Paraíso
    "Vilarinho", // (Santo Tirso or Vila do Conde)
    "Alcanhões",
    "Alferrarede", // Abrantes (São Vicente e São João) e Alferrarede
    "Alpiarça", // Repeated
    "Amiães de Baixo",
    "Azinhaga",
    "Chamusca", // Chamusca e Pinheiro Grande
    "Constância", // Repeated
    "Fátima",
    "Fazendas de Almeirim",
    "Ferreira do Zêzere",
    "Golegã", // Repeated
    "Mação", // Mação, Penhascoso e Aboboreira
    "Montalvinho",
    "Ourém", // Nossa Senhora da Piedade (Ourém)
    "Paialvo",
    "Pego",
    "Pinheiro Grande", // Chamusca e Pinheiro Grande
    "Poceirão", // Poceirão e Marateca
    "Pontével", // Repeated
    "Santa Margarida da Coutada", // Constância (freguesia)
    "Santarém", // (Usually refers to the city/municipality)
    "São Miguel de Rio Torto", // São Miguel do Rio Torto e Rossio ao Sul do Tejo
    "São Vicente do Paul", // São Vicente do Paul e Vale de Figueira
    "Tramagal",
    "Vale de Figueira", // São Vicente do Paul e Vale de Figueira (Santarém) or (Tabuaço)
    "Vale de Santarém",
    "Vila Chã de Ourique", // Repeated
    "Alcácer do Sal", // Alcácer do Sal (Santa Maria do Castelo e Santiago) e Santa Susana
    "Arrentela", // Seixal, Arrentela e Aldeia de Paio Pires
    "Azeitão", // Azeitão (São Lourenço e São Simão)
    "Charneca de Caparica", // Charneca de Caparica e Sobreda
    "Comporta",
    "Grândola", // Grândola e Santa Margarida da Serra
    "Laranjeiro", // Laranjeiro e Feijó
    "Porto Covo",
    "Quinta do Conde",
    "Rosairinho",
    "Santiago do Cacém", // Santiago do Cacém, Santa Cruz e São Bartolomeu da Serra
    "Santo António da Charneca", // Repeated
    "Sarilhos Pequenos",
    "Setúbal", // (Usually refers to the city/municipality)
    "Sines", // Repeated
    "Areosa",
    "Meadela",
    "Melgaço", // Vila e Roussas (Melgaço)
    "Monção", // Monção e Troviscoso
    "Valença", // Valença, Cristelo Covo e Arão
    "Valença", // Repeated
    "Vila Praia de Âncora", // Repeated
    "Alijó",
    "Favaios",
    "Mesão Frio", // Mesão Frio (Santo André)
    "Mondim de Basto",
    "Montalegre", // Montalegre e Padroso
    "Peso da Régua", // Peso da Régua e Godim
    "Ribeira de Pena", // Ribeira de Pena (Salvador) e Santo Aleixo de Além-Tâmega
    "Sabrosa",
    "Santa Marta de Penaguião", // Lobrigos (São Miguel e São João Batista) e Sanhoane
    "Sobreira", // (Paredes)
    "Valpaços", // Valpaços e Sanfins
    "Vila Pouca de Aguiar",
    "Abraveses",
    "Armamar",
    "Cabanas de Viriato",
    "Campo de Besteiros",
    "Canas de Senhorim",
    "Carregal do Sal",
    "Cinfães", // Repeated
    "Ervedosa do Douro",
    "Moimenta da Beira",
    "Mortágua", // Mortágua, Vale de Remígio, Cortegaça e Almaça
    "Oliveira de Frades", // Oliveira de Frades, Souto de Lafões e Sejães
    "Penalva do Castelo",
    "Resende",
    "Rio de Loba",
    "Santa Comba Dão", // Santa Comba Dão e Couto do Mosteiro
    "São João da Pesqueira", // São João da Pesqueira e Várzea de Trevões
    "São João de Areias",
    "São Pedro do Sul", // São Pedro do Sul, Várzea e Baiões
    "Sátão", // Repeated
    "Sernancelhe", // Sernancelhe e Sarzeda
    "Tabuaço", // Repeated
    "Vouzela" // Vouzela e Paços de Vilharigues
];
