<?php

return [
    'action' => [
        'label' => 'Generate impersonation code',
        'modal_heading' => 'Generate impersonation code',
        'modal_description' => 'A temporary code (15 min) will be generated to sign in to the app as this user. The action is logged.',
        'submit' => 'Generate code',
    ],
    'result' => [
        'heading' => 'Impersonation code generated',
        'email_label' => 'Email',
        'code_label' => 'Code',
        'expires_in' => 'Valid for :minutes minutes.',
        'close' => 'Close',
    ],
    'notifications' => [
        'user_not_found' => 'User not found',
        'not_allowed_for_admins' => 'Generating codes for administrators is not allowed',
    ],
    'relation_manager' => [
        'title' => 'Impersonation codes',
        'columns' => [
            'generated_by' => 'Generated by',
            'generated_at' => 'Generated at',
            'expires_at' => 'Expires at',
            'used_at' => 'Used at',
            'failed_attempts' => 'Failed attempts',
            'status' => 'Status',
        ],
        'status' => [
            'active' => 'Active',
            'used' => 'Used',
            'expired' => 'Expired',
            'blocked' => 'Blocked',
        ],
    ],
];
